// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_cognac_RCPPEXPORTS_H_GEN_
#define RCPP_cognac_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace cognac {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("cognac", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("cognac", "_cognac_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in cognac");
            }
        }
    }

    inline std::string GetGenomeId(std::string inStr) {
        typedef SEXP(*Ptr_GetGenomeId)(SEXP);
        static Ptr_GetGenomeId p_GetGenomeId = NULL;
        if (p_GetGenomeId == NULL) {
            validateSignature("std::string(*GetGenomeId)(std::string)");
            p_GetGenomeId = (Ptr_GetGenomeId)R_GetCCallable("cognac", "_cognac_GetGenomeId");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_GetGenomeId(Shield<SEXP>(Rcpp::wrap(inStr)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<std::string >(rcpp_result_gen);
    }

}

#endif // RCPP_cognac_RCPPEXPORTS_H_GEN_
